- hosts: all
  connection: local
  gather_facts: no
  tasks:
   - fail: msg=" Please make sure the variables  id is specified and unique in the command line -e id=uniquedev1"
     when: id is not defined

   - name: Create Instance
     ec2: 
      region="{{ ec2_region }}"
      zone="{{ ec2_zone }}"
      id={{ id }}
      ec2_access_key={{ ec2_access_key }}
      ec2_secret_key={{ ec2_secret_key }}
      keypair={{ ec2_keypair }}
      instance_type={{ ec2_instance_type }} 
      image={{ ec2_image_id }}
      wait=true
      group={{ ec2_group }}
      user_data={{ group_names[0] }}
      instance_tags='{"env":"{{ group_names[0] }}", "id":"{{ id }}"}'
      count={{ count }}
     register: ec2
  

   - name: Wait for the instance to come up
     wait_for: delay=10 host={{ ec2.instances[0].public_ip }} port=22 state=started timeout=360
     with_sequence: start=0 end={{ count|int - 1 }}
   
   - pause: seconds=60

   - name: clone the git repo
     git: repo=http://github.com/bennojoy/netflixoss-ansible.git dest=/opt/bbc1 update=yes
   
   - name: rsync the repo to the newly created instance.
     shell: chdir="/opt/bbc1/ami-creator/ubuntu" ./bootstrap-ami-creator {{ ec2.instances[0].public_ip }}

   - name: Add new instance to host group
     add_host: hostname={{ ec2.instances[0].public_ip }} groupname=ami

- hosts: ami
  user: ubuntu
  tasks:
   - name: Prepare the ami
     shell: chdir="/home/ubuntu/ami-creator/ubuntu" ./01-prepare-ubuntu
     register: step1
   
   - name: Create the ami
     shell: chdir="/home/ubuntu/ami-creator/ubuntu" ./03-create-ami
     register: step2




       
 
